"""PDF and CSV export utilities."""
import csv
import io
import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER

# SiteTrack brand colors
ST_NAVY  = colors.HexColor("#0d1424")
ST_INDIGO = colors.HexColor("#6366f1")
ST_LIGHT = colors.HexColor("#e0e7ff")
ST_MID   = colors.HexColor("#1c2f52")
ST_WHITE = colors.white
ST_WARN  = colors.HexColor("#d97706")
ST_CRIT  = colors.HexColor("#dc2626")

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "reports_output")
os.makedirs(REPORTS_DIR, exist_ok=True)


def generate_pdf(report_name: str, report_type: str, content_md: str,
                 date_from: datetime, date_to: datetime, generated_by: str) -> str:
    """Convert markdown report content to a branded PDF. Returns file path."""
    filename = f"report_{report_type}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)

    doc = SimpleDocTemplate(filepath, pagesize=letter,
                            leftMargin=0.75*inch, rightMargin=0.75*inch,
                            topMargin=0.75*inch, bottomMargin=0.75*inch)

    styles = getSampleStyleSheet()
    style_title = ParagraphStyle("title", fontSize=18, textColor=ST_NAVY,
                                  spaceAfter=6, fontName="Helvetica-Bold")
    style_h1 = ParagraphStyle("h1", fontSize=14, textColor=ST_INDIGO,
                               spaceAfter=4, spaceBefore=12, fontName="Helvetica-Bold")
    style_h2 = ParagraphStyle("h2", fontSize=12, textColor=ST_NAVY,
                               spaceAfter=3, spaceBefore=8, fontName="Helvetica-Bold")
    style_body = ParagraphStyle("body", fontSize=10, textColor=colors.black,
                                 spaceAfter=4, leading=14)
    style_meta = ParagraphStyle("meta", fontSize=9, textColor=colors.grey, spaceAfter=2)

    story = []

    # Header bar
    header_data = [[
        Paragraph("<b>SiteTrack RTLS</b>", ParagraphStyle("hdr", fontSize=14,
                  textColor=ST_WHITE, fontName="Helvetica-Bold")),
        Paragraph("Meridian Industrial", ParagraphStyle("hdr2", fontSize=10,
                  textColor=ST_LIGHT, alignment=2)),
    ]]
    header_table = Table(header_data, colWidths=[3.5*inch, 3.5*inch])
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), ST_NAVY),
        ("TEXTCOLOR", (0, 0), (-1, -1), ST_WHITE),
        ("PADDING", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 0.2*inch))

    # Report title
    story.append(Paragraph(report_name, style_title))
    story.append(Paragraph(
        f"Period: {date_from.strftime('%b %d, %Y')} – {date_to.strftime('%b %d, %Y')}  |  "
        f"Generated by: {generated_by}  |  {datetime.now().strftime('%b %d, %Y %H:%M')}",
        style_meta,
    ))
    story.append(HRFlowable(width="100%", thickness=2, color=ST_INDIGO, spaceAfter=10))

    # Parse markdown content into reportlab elements
    for line in content_md.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.08*inch))
        elif line.startswith("## "):
            story.append(Paragraph(line[3:], style_h1))
        elif line.startswith("### "):
            story.append(Paragraph(line[4:], style_h2))
        elif line.startswith("# "):
            story.append(Paragraph(line[2:], style_title))
        elif line.startswith("- ") or line.startswith("* "):
            story.append(Paragraph(f"• {line[2:]}", style_body))
        elif line.startswith("---"):
            story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
        else:
            line = line.replace("**", "<b>", 1).replace("**", "</b>", 1)
            story.append(Paragraph(line, style_body))

    # Footer
    story.append(Spacer(1, 0.3*inch))
    story.append(HRFlowable(width="100%", thickness=1, color=ST_INDIGO))
    story.append(Paragraph(
        "SiteTrack RTLS | Meridian Industrial | Confidential",
        ParagraphStyle("footer", fontSize=8, textColor=colors.grey, alignment=TA_CENTER),
    ))

    doc.build(story)
    return filepath


def generate_csv(data: list[dict], filename_prefix: str) -> str:
    """Write list of dicts to a CSV file. Returns file path."""
    if not data:
        return ""
    filename = f"{filename_prefix}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
    filepath = os.path.join(REPORTS_DIR, filename)
    with open(filepath, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(data[0].keys()))
        writer.writeheader()
        writer.writerows(data)
    return filepath
